name: Build Documentation

on:
  # lors d'un push sur la branche feature/US4
  push:
    branches: [feature/US4]
  pull_request:
    branches: [feature/US4]
jobs:
  #génération de la doccumentation
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # on configure python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
      # on installe les dépendances nécessaires à la génération
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Build documentation
      # on se place dans le dossier doc et on génère la documentation
        run: |
          cd doc
          make html

      - name: Deploy to GitHub Pages
      # on déploie uniquement si on est sur la branche main
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3